# Numpy

In [1]:
import numpy as np

## Numpy Arrays
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Creating Numpy Arrays

### 1. From python list

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### 1. arange
returns evenly spaced values within a given interval. 

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### 2. zeros and ones
Generate arrays of zeros or ones

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((4,3)) # 4 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((4,3)) # 4 rows and 3 columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 3. With specific values

In [16]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### 4. Identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 5. linspace
Returns evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### 6. rand
Create an array of the given shape and populate it with random samples from a uniform distribution over (0,1)

In [23]:
np.random.rand(10)

array([0.0847934 , 0.20804998, 0.87775975, 0.47838012, 0.2036345 ,
       0.89530808, 0.08258075, 0.94201915, 0.25457874, 0.87637242])

In [24]:
np.random.rand(3,3)

array([[0.87520303, 0.41604947, 0.77881324],
       [0.09922028, 0.30068196, 0.88068823],
       [0.32610396, 0.83827938, 0.5692916 ]])

### 7. randn
Return a sample from the "standard normal" distribution. 

In [25]:
np.random.randn(6)

array([ 1.49536426, -0.31195077,  0.17804902,  0.95728129,  0.29335684,
        0.07961459])

In [26]:
np.random.randn(3,3)

array([[ 0.12148504,  1.40221287, -0.05764303],
       [-0.901787  , -0.7206354 , -1.09752149],
       [-1.19658946,  0.8359538 , -1.07462222]])

### 8. randint
Return random integers from low (inclusive) to high (exclusive)

In [27]:
np.random.randint(1,50)

32

In [28]:
np.random.randint(0,10,(3,3))

array([[5, 0, 7],
       [7, 4, 5],
       [3, 2, 4]])

In [29]:
np.random.randint(0,50,5)

array([14, 21, 46, 29, 46])

## Array Attributes and Methods

In [30]:
arr = np.arange(25)
arr2 = np.random.randint(0,50,10)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [32]:
arr2

array([ 7,  2, 29, 31, 28, 44, 11, 40,  0, 16])

### 1. Reshape
Returns an array containing the same data with new shape

In [33]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

### 2. max, min, argmax, argmin
Useful methods for finding max or min values.

In [34]:
arr2.max()

44

In [36]:
arr2.argmax() # returns index of the max value

5

In [37]:
arr2.min()

0

In [39]:
arr2.argmin() # returns index of the min value

8

### 3. Shape

In [40]:
arr.shape

(25,)

In [41]:
arr.reshape(1,25)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24]])

In [42]:
arr.reshape(25,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11],
       [12],
       [13],
       [14],
       [15],
       [16],
       [17],
       [18],
       [19],
       [20],
       [21],
       [22],
       [23],
       [24]])

In [44]:
arr.ndim

1

In [45]:
arr.reshape(1,25).ndim

2

### 4. dtype

In [46]:
arr.dtype

dtype('int64')

# Indexing and Selection

In [47]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

## 1. Bracket Indexing and Selection

In [48]:
arr[8]

8

In [49]:
arr[1:5]

array([1, 2, 3, 4])

In [50]:
arr[0:5]

array([0, 1, 2, 3, 4])

### 2D array

In [60]:
my_arr = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
my_arr


array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [54]:
my_arr[1,2] # 1st row and 2nd column. Starts from 0th.

7

In [55]:
my_arr[1] # 2nd row (Start from 0th count)

array([5, 6, 7, 8])

In [57]:
my_arr[:,2] # 3rd column (Starts from 0th count)

array([ 3,  7, 11])

In [59]:
my_arr[0:2,1:3]

array([[2, 3],
       [6, 7]])

## Broadcasting

In [61]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [62]:
arr[0:5] = 100
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [64]:
arr = np.arange(0,11)
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [65]:
slice_of_arr = arr[0:6]
slice_of_arr

array([0, 1, 2, 3, 4, 5])

In [66]:
slice_of_arr[:] = 99
slice_of_arr

array([99, 99, 99, 99, 99, 99])

In [68]:
arr
# Original array changed which basically means data is not copied. Meaning "slice_of_arr" doesn't have separate memory which avoids memory problems

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

### Indexing a 2D array (matrices)
Format is **arr_2d[row][col]** or **arr_2d[row,col]**

In [70]:
arr_2d = np.array(([5,10,15],[20,25,30],[35,40,45],[50,55,60]))
arr_2d # 4 rows and 3 columns

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [71]:
arr_2d[1] # row

array([20, 25, 30])

In [72]:
arr_2d[1][0] # individual element

20

In [73]:
arr_2d[1,0] # same as above

20

In [74]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45],
       [50, 55, 60]])

In [75]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [76]:
arr_2d[3]

array([50, 55, 60])

In [78]:
arr_2d[:,1] # Column

array([10, 25, 40, 55])

### Fancy Indexing

In [80]:
arr2d = np.zeros((10,10))
arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [81]:
arr2d.shape

(10, 10)

In [82]:
arr_length  = arr2d.shape[1]
arr_length

10

In [83]:
for i in range(arr_length):
    arr2d[i] = i 

arr2d

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1., 1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3., 3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [5., 5., 5., 5., 5., 5., 5., 5., 5., 5.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [7., 7., 7., 7., 7., 7., 7., 7., 7., 7.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.],
       [9., 9., 9., 9., 9., 9., 9., 9., 9., 9.]])

In [84]:
arr2d[[2,4,6,8]]

array([[2., 2., 2., 2., 2., 2., 2., 2., 2., 2.],
       [4., 4., 4., 4., 4., 4., 4., 4., 4., 4.],
       [6., 6., 6., 6., 6., 6., 6., 6., 6., 6.],
       [8., 8., 8., 8., 8., 8., 8., 8., 8., 8.]])

In [85]:
arr2d[:,[2,4,6,8]]

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.],
       [8., 8., 8., 8.],
       [9., 9., 9., 9.]])

In [86]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9, 10])

In [88]:
arr = np.arange(1,11)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [89]:
bool_arr = arr>4

In [90]:
arr[bool_arr]

array([ 5,  6,  7,  8,  9, 10])

In [91]:
x = 2 
arr[arr>x]

array([ 3,  4,  5,  6,  7,  8,  9, 10])

## Numpy Operations

In [92]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [93]:
arr + arr

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [94]:
arr * arr

array([  1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [95]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [96]:
arr / arr

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [98]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [97]:
1/arr

array([1.        , 0.5       , 0.33333333, 0.25      , 0.2       ,
       0.16666667, 0.14285714, 0.125     , 0.11111111, 0.1       ])

### Universal Array Functions

In [99]:
np.sqrt(arr)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798,
       2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766])

In [100]:
np.exp(arr)

array([2.71828183e+00, 7.38905610e+00, 2.00855369e+01, 5.45981500e+01,
       1.48413159e+02, 4.03428793e+02, 1.09663316e+03, 2.98095799e+03,
       8.10308393e+03, 2.20264658e+04])

In [101]:
np.max(arr)

10

In [102]:
np.sin(arr)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 , -0.95892427,
       -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849, -0.54402111])

In [103]:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])