# Numpy

In [1]:
import numpy as np

## Numpy Arrays
Numpy arrays essentially come in two flavors: vectors and matrices. Vectors are strictly 1-d arrays and matrices are 2-d (but you should note a matrix can still have only one row or one column).

## Creating Numpy Arrays

### 1. From python list

In [2]:
my_list = [1,2,3]
np.array(my_list)

array([1, 2, 3])

In [3]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]]
np.array(my_matrix)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

## Built-in Methods

### 1. arange
returns evenly spaced values within a given interval. 

In [4]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
np.arange(0,10,2)

array([0, 2, 4, 6, 8])

### 2. zeros and ones
Generate arrays of zeros or ones

In [6]:
np.zeros(3)

array([0., 0., 0.])

In [12]:
np.zeros((4,3)) # 4 rows and 3 columns

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [8]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones((4,3)) # 4 rows and 3 columns

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

### 3. With specific values

In [16]:
np.full((4,3),7)

array([[7, 7, 7],
       [7, 7, 7],
       [7, 7, 7],
       [7, 7, 7]])

### 4. Identity matrix

In [17]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

### 5. linspace
Returns evenly spaced numbers over a specified interval.

In [20]:
np.linspace(0,10,3)

array([ 0.,  5., 10.])

In [21]:
np.linspace(0,10,5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [22]:
np.linspace(0,20,10)

array([ 0.        ,  2.22222222,  4.44444444,  6.66666667,  8.88888889,
       11.11111111, 13.33333333, 15.55555556, 17.77777778, 20.        ])

### 6. rand
Create an array of the given shape and populate it with random samples from a uniform distribution over (0,1)

In [23]:
np.random.rand(10)

array([0.0847934 , 0.20804998, 0.87775975, 0.47838012, 0.2036345 ,
       0.89530808, 0.08258075, 0.94201915, 0.25457874, 0.87637242])

In [24]:
np.random.rand(3,3)

array([[0.87520303, 0.41604947, 0.77881324],
       [0.09922028, 0.30068196, 0.88068823],
       [0.32610396, 0.83827938, 0.5692916 ]])

### 7. randn
Return a sample from the "standard normal" distribution. 

In [25]:
np.random.randn(6)

array([ 1.49536426, -0.31195077,  0.17804902,  0.95728129,  0.29335684,
        0.07961459])

In [26]:
np.random.randn(3,3)

array([[ 0.12148504,  1.40221287, -0.05764303],
       [-0.901787  , -0.7206354 , -1.09752149],
       [-1.19658946,  0.8359538 , -1.07462222]])

### 8. randint
Return random integers from low (inclusive) to high (exclusive)

In [27]:
np.random.randint(1,50)

32

In [28]:
np.random.randint(0,10,(3,3))

array([[5, 0, 7],
       [7, 4, 5],
       [3, 2, 4]])