# Pandas

In [1]:
import numpy as np
import pandas as pd

## Series
Similar to numpy array. Difference between Numpy array and Series, is that a Series can have axis labels, meaning it can be indexed by a label, instead of just number location. It also doesn't need to hold numeric data, it can hold any arbitrary Python Object.

### Creating a Series

In [2]:
labels = ['a','b','c','d']
my_list = [10,20,30,40]
arr = np.array([10,20,30,40])
d = {'a':10,'b':20,'c':30,'d':40}

#### 1. Using Lists

In [3]:
pd.Series(data = my_list)

0    10
1    20
2    30
3    40
dtype: int64

In [4]:
pd.Series(data=my_list, index=labels)

a    10
b    20
c    30
d    40
dtype: int64

In [6]:
pd.Series(my_list,labels)

a    10
b    20
c    30
d    40
dtype: int64

#### 2. Numpy Arrays

In [7]:
pd.Series(arr)

0    10
1    20
2    30
3    40
dtype: int64

In [8]:
pd.Series(arr,labels)

a    10
b    20
c    30
d    40
dtype: int64

#### 3. Dictionaries

In [9]:
pd.Series(d)

a    10
b    20
c    30
d    40
dtype: int64

#### Data in a Series

In [10]:
pd.Series(data=labels, index=my_list)

10    a
20    b
30    c
40    d
dtype: object

**Sereis can hold functions also.**

In [11]:
pd.Series([sum,print,len])

0      <built-in function sum>
1    <built-in function print>
2      <built-in function len>
dtype: object

### Using an Index.
The key to using Series is understanding its index. Pandas makes use of these index names or numbers by allowing for fast look ups of information

In [12]:
ser1 = pd.Series([1,2,3,4], index=['USA','Germany','USSR','Japan'])

In [13]:
ser1

USA        1
Germany    2
USSR       3
Japan      4
dtype: int64

In [14]:
ser2 = pd.Series([1,2,5,4], index=['USA','Germany','Italy','Japan'])

In [15]:
ser2

USA        1
Germany    2
Italy      5
Japan      4
dtype: int64

In [16]:
ser1['USA']

1

In [18]:
ser1 + ser2

Germany    4.0
Italy      NaN
Japan      8.0
USA        2.0
USSR       NaN
dtype: float64

## DataFrames
DataFrames are bunch of Series objects put togather to share same index. 

In [19]:
from numpy.random import randn 
np.random.seed(101)

In [21]:
np.random.randn(5,4)

array([[ 2.70684984,  0.62813271,  0.90796945,  0.50382575],
       [ 0.65111795, -0.31931804, -0.84807698,  0.60596535],
       [-2.01816824,  0.74012206,  0.52881349, -0.58900053],
       [ 0.18869531, -0.75887206, -0.93323722,  0.95505651],
       [ 0.19079432,  1.97875732,  2.60596728,  0.68350889]])

In [24]:
df = pd.DataFrame(randn(5,4), index = 'A B C D E'.split(), columns = 'Sid Karan Kushal Anuraag'.split())

In [25]:
df

Sid     Karan    Kushal   Anuraag
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

### Selection and Indexing

##### Selecting a column or columns

In [26]:
df['Sid']

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: Sid, dtype: float64

In [27]:
df[['Sid','Karan']]

Sid     Karan
A -0.993263  0.196800
B  1.025984 -0.156598
C  2.154846 -0.610259
D  0.147027 -0.479448
E -0.925874  1.862864

In [28]:
df.Sid

A   -0.993263
B    1.025984
C    2.154846
D    0.147027
E   -0.925874
Name: Sid, dtype: float64

In [30]:
type(df.Sid) # Columns are just Series

pandas.core.series.Series

#### Creating a new column:

In [31]:
df['new'] = df['Sid'] + df['Karan']
df

Sid     Karan    Kushal   Anuraag       new
A -0.993263  0.196800 -1.136645  0.000366 -0.796464
B  1.025984 -0.156598 -0.031579  0.649826  0.869386
C  2.154846 -0.610259 -0.755325 -0.346419  1.544588
D  0.147027 -0.479448  0.558769  1.024810 -0.332421
E -0.925874  1.862864 -1.133817  0.610478  0.936990

#### Removing Columns

In [32]:
df.drop('new', axis=1)

Sid     Karan    Kushal   Anuraag
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [51]:
df # Original dataframe will not affected by this. Unless you use "inplace", it will not drop or change orginal dataframe.

Sid     Karan    Kushal   Anuraag       new
A -0.993263  0.196800 -1.136645  0.000366 -0.796464
B  1.025984 -0.156598 -0.031579  0.649826  0.869386
C  2.154846 -0.610259 -0.755325 -0.346419  1.544588
D  0.147027 -0.479448  0.558769  1.024810 -0.332421
E -0.925874  1.862864 -1.133817  0.610478  0.936990

In [52]:
df.drop('new', axis=1, inplace=True)
df

Sid     Karan    Kushal   Anuraag
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [55]:
df.drop('E', axis=0)

Sid     Karan    Kushal   Anuraag
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [35]:
df.sum(axis=1)

A   -2.729206
B    2.357019
C    1.987431
D    0.918737
E    1.350641
dtype: float64

#### Understing SUM function in Numpy and Pandas on axis. 
row = axis=0 sums vertically (down the columns)

Column = axis=1 sums horizontally (across the rows)

In [36]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [47]:
data = pd.DataFrame(arr, index = 'a b c'.split(), columns='Sid Shubu Vedya'.split())
data

Sid  Shubu  Vedya
a    1      2      3
b    4      5      6
c    7      8      9

In [48]:
print(arr.sum(axis=1))
print(data.sum(axis=1))

[ 6 15 24]
a     6
b    15
c    24
dtype: int64


In [49]:
print(arr.sum(axis=0))
print(data.sum(axis=0))

[12 15 18]
Sid      12
Shubu    15
Vedya    18
dtype: int64


### Selecting Rows

In [56]:
df

Sid     Karan    Kushal   Anuraag
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [57]:
df.loc['A']

Sid       -0.993263
Karan      0.196800
Kushal    -1.136645
Anuraag    0.000366
Name: A, dtype: float64

In [59]:
df.iloc[0] # based off of position instead of label

Sid       -0.993263
Karan      0.196800
Kushal    -1.136645
Anuraag    0.000366
Name: A, dtype: float64

In [61]:
df.loc['B','Sid']

1.025984152081572

In [62]:
df.loc[['A','B'],['Sid','Kushal']]

Sid    Kushal
A -0.993263 -1.136645
B  1.025984 -0.031579

### Conditional Selection

In [63]:
df

Sid     Karan    Kushal   Anuraag
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [64]:
df[df>0]

Sid     Karan    Kushal   Anuraag
A       NaN  0.196800       NaN  0.000366
B  1.025984       NaN       NaN  0.649826
C  2.154846       NaN       NaN       NaN
D  0.147027       NaN  0.558769  1.024810
E       NaN  1.862864       NaN  0.610478

In [65]:
df[df['Sid']>0]

Sid     Karan    Kushal   Anuraag
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [66]:
df[df['Sid']>0]['Anuraag']

B    0.649826
C   -0.346419
D    1.024810
Name: Anuraag, dtype: float64

In [67]:
df[df['Sid']>0][['Karan','Kushal','Anuraag']]

Karan    Kushal   Anuraag
B -0.156598 -0.031579  0.649826
C -0.610259 -0.755325 -0.346419
D -0.479448  0.558769  1.024810

#### For two conditions you can use | and & with parenthesis

In [71]:
df[(df['Sid']>0) & (df['Karan']<0)]

Sid     Karan    Kushal   Anuraag
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810

In [72]:
df[(df['Sid']>0) & (df['Karan']<0)][['Kushal','Anuraag']]

Kushal   Anuraag
B -0.031579  0.649826
C -0.755325 -0.346419
D  0.558769  1.024810

### More Index Details

In [73]:
df

Sid     Karan    Kushal   Anuraag
A -0.993263  0.196800 -1.136645  0.000366
B  1.025984 -0.156598 -0.031579  0.649826
C  2.154846 -0.610259 -0.755325 -0.346419
D  0.147027 -0.479448  0.558769  1.024810
E -0.925874  1.862864 -1.133817  0.610478

In [74]:
df.reset_index()

index       Sid     Karan    Kushal   Anuraag
0     A -0.993263  0.196800 -1.136645  0.000366
1     B  1.025984 -0.156598 -0.031579  0.649826
2     C  2.154846 -0.610259 -0.755325 -0.346419
3     D  0.147027 -0.479448  0.558769  1.024810
4     E -0.925874  1.862864 -1.133817  0.610478

In [80]:
new = 'CA TX NY AZ CO'.split()

In [81]:
df['States'] = new

In [82]:
df

Sid     Karan    Kushal   Anuraag States
A -0.993263  0.196800 -1.136645  0.000366     CA
B  1.025984 -0.156598 -0.031579  0.649826     TX
C  2.154846 -0.610259 -0.755325 -0.346419     NY
D  0.147027 -0.479448  0.558769  1.024810     AZ
E -0.925874  1.862864 -1.133817  0.610478     CO

In [83]:
df.set_index('States')

Sid     Karan    Kushal   Anuraag
States                                        
CA     -0.993263  0.196800 -1.136645  0.000366
TX      1.025984 -0.156598 -0.031579  0.649826
NY      2.154846 -0.610259 -0.755325 -0.346419
AZ      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478

In [84]:
df

Sid     Karan    Kushal   Anuraag States
A -0.993263  0.196800 -1.136645  0.000366     CA
B  1.025984 -0.156598 -0.031579  0.649826     TX
C  2.154846 -0.610259 -0.755325 -0.346419     NY
D  0.147027 -0.479448  0.558769  1.024810     AZ
E -0.925874  1.862864 -1.133817  0.610478     CO

In [85]:
df.set_index('States', inplace=True)

In [86]:
df

Sid     Karan    Kushal   Anuraag
States                                        
CA     -0.993263  0.196800 -1.136645  0.000366
TX      1.025984 -0.156598 -0.031579  0.649826
NY      2.154846 -0.610259 -0.755325 -0.346419
AZ      0.147027 -0.479448  0.558769  1.024810
CO     -0.925874  1.862864 -1.133817  0.610478

### Multi-Index and Index Hierarchy

In [3]:
arrays = [["A","A","B","B"], ["one","two","one","two"]]
index = pd.MultiIndex.from_arrays(arrays,names=("letters","numbers"))

In [7]:
index

MultiIndex([('A', 'one'),
            ('A', 'two'),
            ('B', 'one'),
            ('B', 'two')],
           names=['letters', 'numbers'])

In [4]:
data = {
    "value1": [10,15,20,25],
    "value2": [5,10,15,20]
}

In [5]:
df = pd.DataFrame(data, index=index)
df

value1  value2
letters numbers                
A       one          10       5
        two          15      10
B       one          20      15
        two          25      20

In [6]:
df.loc["A"]

value1  value2
numbers                
one          10       5
two          15      10

In [8]:
df.loc["A"].loc["one"]

value1    10
value2     5
Name: one, dtype: int64

In [10]:
df.loc["A"].iloc[0]

value1    10
value2     5
Name: one, dtype: int64

In [11]:
df.index.names

FrozenList(['letters', 'numbers'])

In [13]:
df

value1  value2
letters numbers                
A       one          10       5
        two          15      10
B       one          20      15
        two          25      20

In [12]:
df.xs('A')

value1  value2
numbers                
one          10       5
two          15      10

In [14]:
df.xs(['A','one'])

/var/folders/lq/bb09dcm13557jqlh7zyq8n_c0000gn/T/ipykernel_2498/260856957.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['A','one'])


value1    10
value2     5
Name: (A, one), dtype: int64

In [15]:
df.xs(['A','one'])[1]

/var/folders/lq/bb09dcm13557jqlh7zyq8n_c0000gn/T/ipykernel_2498/1942387579.py:1: FutureWarning: Passing lists as key for xs is deprecated and will be removed in a future version. Pass key as a tuple instead.
  df.xs(['A','one'])[1]


5

In [16]:
df.xs('two',level='numbers')

value1  value2
letters                
A            15      10
B            25      20

## Missing Data

Pandas provides several methods and functions to work with missing values. Here's a comprehensive list of the most commonly used ones:

**1. Detecting missing values:**

isna() / isnull(): Detect missing values

notna() / notnull(): Detect non-missing values

**2 .Filling missing values:**

fillna(): Fill NA/NaN values using the specified method.

bfill() / backfill(): Backward fill NA/NaN values.

ffill() / pad(): Forward fill NA/NaN values.

interpolate(): Interpolate values according to different methods

**3. Dropping missing values:**

dropna(): Remove missing values

drop_duplicates(): Remove duplicate rows (can be used with subset parameter to consider only specific columns)

**4. Replacing values:**

replace(): Replace values given in 'to_replace' with 'value'

**5. Aggregation functions (with skipna parameter):**

sum(), mean(), median(), min(), max(), etc.

**6. Handling missing values in groupby operations:**

groupby().agg() with custom functions

groupby().transform() for filling group-specific values

**7. Mask operations:**

mask(): Replace values where the condition is True

where(): Replace values where the condition is False

**8. Time series-specific methods:**

asfreq(): Convert time series to specified frequency, can fill missing values

reindex(): Conform Series/DataFrame to new index, can fill missing values

**9. Covariance and correlation:**

cov(): Compute pairwise covariance, can handle missing values

corr(): Compute pairwise correlation, can handle missing values

**10. Windowing operations:**

rolling(): Provide rolling window calculations, can handle missing values

expanding(): Provide expanding transformations, can handle missing values

**11. String methods:**

str accessor methods like str.replace(), str.extract(), etc., can handle missing values

**12. Categorical operations:**

Categorical.add_categories(): Add new categories, can fill missing values

Categorical.remove_unused_categories(): Remove unused categories, can affect missing value representation

**13. MultiIndex operations:**

reindex() with fill_value parameter for multi-index Series/DataFrames

**14. Merge and join operations:**

merge(), join(): Can handle missing values during combining datasets

**15. Pivot and reshape operations:**

pivot_table(): Can specify how to handle missing values

melt(): Can affect how missing values are represented in long format

**16. IO operations:**

read_csv(), read_excel(), etc., with na_values parameter to specify additional strings to recognize as NA/NaN

**17. Data type conversion:**

astype(): Convert to a specified dtype, can affect how missing values are represented

**18. Indexing with missing values:**

loc[], iloc[]: Can be used to select or modify data including missing values

In [17]:
df = pd.DataFrame({'A':[1,2,np.nan],
                   'B':[5,np.nan,np.nan],
                   'C':[1,2,3]})

df

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2
2  NaN  NaN  3

In [20]:
df.dropna() # drops rows which contains null or missing values

A    B  C
0  1.0  5.0  1

In [19]:
df.dropna(axis=1) # drops columns

C
0  1
1  2
2  3

In [21]:
df.dropna(thresh=2) # Keep rows that has atleast 2 non NaN values

A    B  C
0  1.0  5.0  1
1  2.0  NaN  2

In [30]:
df.dropna(thresh=2, axis=1) # keeps columns that has atleast 2 non NaN values



A  C
0  1.0  1
1  2.0  2
2  NaN  3

In [31]:
df.fillna(value='FILL VALUE')

A           B  C
0         1.0         5.0  1
1         2.0  FILL VALUE  2
2  FILL VALUE  FILL VALUE  3

In [32]:
df['A'].fillna(value=df['A'].mean())

0    1.0
1    2.0
2    1.5
Name: A, dtype: float64

### Another example of Missing value and it's handling